[package]
name = "rustmatic-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustmatic = { workspace = true }
rustmatic-script = { workspace = true }